### PR TITLE
Icons: standardize images

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes https://github.com/international-labour-organization/designsystem/issues/839

### Notes

* This PR is in charge of standardising the icon images to maintain a consistent size. 

### Steps followed

- [x] Remove unused icons
- [x] Add new icons
- [x] Replace existing icons
- [x] Refactor existing implementation of where the icons are used.

### New Icons added

ArrowGoToLeft
ArrowSort
Calendar
Upload
NotificationInfo
Conference
Settings
Statistics Launch
Online Mail
Pin
Send
Share
ClosedCaptions 
ChevronUp
ChevronLeft
ChevronRight
CaretUp
CaretLeft

### Replaced Icons 

Add
Arrow -> ArrowDown
ArrowUp
BreadcrumbDividerRTL -> ArrowLeft
PaginationArrow/ BreadcrumbDivider -> ArrowRight 
Burger
CheckMark -> Check
Download
DoubleArrow-> ArrowGoToRight	
Home
Copyright
Play Pause
Facebook -> SocialFacebook
Instagram -> SocialInstagram
Flickr -> SocialFlickr
RSS -> SocialRss
X -> SocialX
LinkedIn -> SocialLinkedIn
TikTok -> SocialTiktok
Elipsis -> DotMenu
Global -> Language 
Error -> NotifcationError
Error Info -> NotificationInfoOutlined
Success -> NotificationSuccess
Warning -> NotificationWarning
Search 
Minus
Muted -> VideoSoundOff 
Volume -> VideoSoundOn
SteMarrow -> ChevronDown
ListArrow-> CaretRight
Equilateraltriangle -> CaretDown
 
### Used Old icons not available on the design 

Quote
FooterTriangle
HalfSquareTriangle

### Unused Old icons 

Scalenerighttriangle
Scalenerighttrianglereverse
TriangleDecoration
TriangleReverse
ListArrowReverse
Triangle

### CODE REVIEW

**Comment by Shashika6** [comment]
Hey @justintemps I'm done with the implementation for this but I will have to check components individually to see if the icons are aligned properly cause the sizes of the icons changed along with this implementation. Will do a proper testing round again to see if everything is as expected.

**Comment by justintemps** [comment]
Hey @Shashika6, lots to fix here:

- [ ]  The arrows are missing from the [breadcrumb](https://deploy-preview-1208--ilo-ui-twig-develop.netlify.app/?path=/docs/components-navigation-breadcrumb--docs)
- [ ] The icons are too small in the [social media](https://deploy-preview-1208--ilo-ui-twig-develop.netlify.app/?path=/docs/components-navigation-social-media--docs) component
- [ ] The triangles are too small in the [unordered List](https://deploy-preview-1208--ilo-ui-twig-develop.netlify.app/?path=/docs/components-content-list--docs) component.
- [ ] Same thing for the LinkList Component
- [ ] Check the arrow in the [profile component](https://twig.ui.ilo.org/?path=/docs/components-content-profile--docs) it looks different from the one we have now
- [ ] [Table of contents] down arrows look too big.
- [ ] In the [Button](https://twig.ui.ilo.org/?path=/docs/components-user-interface-button--docs), many of the icons are too big or out of place. Why is this still happening?
- [ ] Same issue for the [Icon](https://twig.ui.ilo.org/?path=/docs/components-user-interface-icon--docs) component (this is probably the cause of the button component problem).
- [ ] Icons are missing from the Tab component
- [ ] the icons are too small in the Callout components
- [ ] Same thing for the Notification component
- [ ] Arrow alignment is broken in the [Detail Card](https://twig.ui.ilo.org/?path=/story/components-cards-detail-card--default&args=dateExtra:20+September+2022)

**Comment by Shashika6** [comment]
Sure @justintemps Will have a look at all these and check the components again as well.

**Comment by justintemps** [comment]
Hey @Shashika6 could you resolve the merge conflict here?

**Comment by Shashika6** [comment]
Hey @justintemps I resolved the conflicts looks like the design team needs a few more icons added.

**Comment by Shashika6** [comment]
Hey @justintemps Ill be creating a new issue for the changes requested by design as there is quite a few changes to be done on the footer component this is ready to be merged now 🎉

**Comment by justintemps** [comment]
Thanks @Shashika6, before I can merge this, I need @GGKapanadze to clear up this one in the ilo site builder repo: https://github.com/international-labour-organization/designsystem-site-builder/issues/8

**Comment by justintemps** [comment]
Hey @Shashika6, can you check 2 things for me?

1. I think you mixed up arrows and chevrons. Can you check that's what they're called in the design system?
2. Can I confirm that, in general, the names give to the icons are the same as the ones used in Figma?

**Pull request merged**
