### PR TITLE
(feat/twig) add socialmedia component

### LINKED ISSUE #366: Create social media component
Create social media component with full list of icons:
- Facebook
- LinkedIn
- Twitter
- Instagram
- Tiktok
- Flickr
- Youtube
- Vimeo

### PR DESCRIPTION
**Pull request by wc-lei**
## Social media component in Twig and React

This adds a new Social Media component that renders a list of social media icons with links. The following social networks are supported:

- Twitter
- Facebook
- Instagram
- LinkedIn
- TikTok
- Flickr
- Instagram

See the relative Storybooks for documentation and usage.

## ⚠️ Breaking changes in a minor relase

This PR includes breaking changes in a minor release. This is tolerated while the Design System is in <v1.0.0. [See details below for upgrading to the new release](https://github.com/international-labour-organization/designsystem/pull/423#issuecomment-1639828929)

Fixes #366

### CODE REVIEW

**Comment by justintemps** [comment]
## ⚠️ Breaking changes in a minor release

This PR adds a new Social Media component and then uses that component to render the social media icons in the Hero Card and Footer components. In the process, some property names have changed.

## Description of changes in Twig

The `socials` property in the **HeroCard** and **Footer** components is replaced with a `socialmedia` property which passes down properties to the underlying **Social Media** component.

Example:

```yaml
...
socialmedia:
  icons:
    - label: "Facebook"
      url: "https://www.facebook.com/"
      icon: "facebook"
    - label: "Linkedin"
      url: "https://www.linkedin.com/"
      icon: "linkedin"
...
```

**Comment by justintemps** [comment]
@inesdgomes could you kindly review this?

- [ ] [New twig social media component](https://deploy-preview-423--ilo-ui-twig.netlify.app/?path=/docs/components-social-media--social-media)
- [ ] [Used in the Hero Card](https://deploy-preview-423--ilo-ui-twig.netlify.app/?path=/docs/components-hero-card--hero-card)
- [ ] [Used in the Hero](https://deploy-preview-423--ilo-ui-twig.netlify.app/?path=/docs/components-hero--default)
- [ ] [Used in the Footer](https://deploy-preview-423--ilo-ui-twig.netlify.app/?path=/docs/components-footer--footer)

Make sure to view in Canvas mode to get the full width on desktop and to narrow the viewport to check for mobile.

**Comment by inesdgomes** [comment]
@justintemps All looks good to me, except for the sizes - they don't have consistent sizes. According to the design files, all icons should have the same width (16px), except for TikTok which should be 14px.

**Comment by justintemps** [comment]
I think that's because there are different amounts of white space around the icons in the svg files. See here:

facebook
flickr

**Pull request merged**
