### PR TITLE
ILO Theme Foundation

### PR DESCRIPTION
**Pull request by GGKapanadze**
## Foundation 

The PR introduces the foundation file mentioned in #999. The foundation file has 2 primary sources, the first one is the **Figma** foundation file, and the second one is the old token system or actual source code. There is also a third-ish one I named it **Mixed**, part from source code and part from Figma components

Foundation file 
✅ - Implemented
🚧 - Partially
⛔ - Not Implemented

| Scope | Status | Soure | 
|--------|--------|------|
| Colors | ✅ | Figma | 
| Typography | 🚧 |  Mixed | 
| Sizing | ✅ |  Figma | 
| Spacing | ✅ | Figma | 
| Breakpoints | ✅ | Source Code | 
| Transitions | ✅ |  Source Code | 
| Borders | ✅ |  Source Code | 

### Typography
 
Typograph is marked as not implemented because we need a Figma update for #896, but it has a main port of the current token system

### Mixins

Two widely used mixins were refactored
-  `spacing` mixin now is fully powered by a new foundation
-  `breakpoint` mixin was a bit problematic because referencing CSS variables as a media query value isn't possible without `js` interaction so I have used SCSS variables to define the breakpoints(for mixing usage) and also composed `CSS` variables from those, `SCSS`version of variables aren't directly referenced by any property it's only used for breakpoint mixin. 

### Found Figma Problems
We have 2 green colors, so I made the second one, `green-light`
image

### Prefixes

All foundation variables are prefixed as proposed in #999. Prefixes are static for now, but they can be implemented with concatenation if we really want to make it "dynamic".  I still suggest to keep it static for now because it's better for visual feedback, referencing and general readability, after we agree about "composability" of the designsystem we can always do plain old find and replace for `--ilo`

### CODE REVIEW

**Comment by justintemps** [comment]
Hey @GGKapanadze I love the direction here, this all looks fine, I'm still undecided about the prefixes. However, I was noticing that the main css bundle has gone from 271kb in the current release to 421kb in this one. I didn't have the chance to dig in and figure out why that was happening, do you have any ideas?

**Comment by justintemps** [comment]
Hey @GGKapanadze actually I had a look and it seems like the root variables are all getting prepended to each class for some reason

**Comment by GGKapanadze** [comment]
I'll try to fix it, I think it's about import resolution

**Comment by justintemps** [comment]
Hey @GGKapanadze before I look at this again, did you have a second to look at the import resolution?

**Comment by GGKapanadze** [comment]
@justintemps The issue was caused by the `scss` variable import inside the mixin, which importing the full `:root` definition for every file that was using the `mixins.scss`

> Old
Alacritty 2024-06-13 00 34 03

> New
Alacritty 2024-06-13 00 33 21

**Comment by justintemps** [comment]
Hey @GGKapanadze , I was trying to test this out in bb8, but then I hit this error: https://github.com/international-labour-organization/designsystem-site-builder/issues/6

Could you have a look?

**Comment by Shashika6** [comment]
Fixed the e2e test for tooltip. :')

Cc :- @justintemps @GGKapanadze

**Pull request merged**
