### PR TITLE
fix(twig) - Make language selector optional in nav/ local nav

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes :- https://github.com/international-labour-organization/designsystem/issues/740

Notes :- 

* Currently nav and local nav will always display the language selector this needs to be made optional.

Screenshots :- 

### Nav

Before Big screen

Screenshot 2023-12-20 at 15 16 30

After Big screen

Screenshot 2023-12-20 at 15 42 13

Before Small screen

Screenshot 2023-12-20 at 15 19 47

After Small screen

Screenshot 2023-12-20 at 15 47 04

### Local Nav

Before Big screen

Screenshot 2023-12-20 at 15 35 29

After Big screen
Screenshot 2023-12-20 at 15 35 02

Before Small screen

Screenshot 2023-12-20 at 15 34 35

After Small screen

Screenshot 2023-12-20 at 15 35 13

### CODE REVIEW

**Comment by Shashika6** [comment]
@justintemps Did the changes to not show the language selector when it is empty. Like you said we will need @inesdgomes to have a look at it to see if the designs are okay for the state where it is empty.

**Comment by justintemps** [comment]
@inesdgomes for you to check when you come back. CC @dali-ilo

**Comment by justintemps** [comment]
Thanks @Shashika6, as discussed with @inesdgomes the dark blue background behind the language selector should also be removed when the language selector isn't there:

image

**Comment by justintemps** [comment]
Hey @inesdgomes , @Shashika6 pushed up a fix but the height of the header changes a little. Is that ok?


https://github.com/international-labour-organization/designsystem/assets/12401179/c75bd7fb-ad33-408a-9090-5a1bb214a412

**Comment by Shashika6** [comment]
@justintemps @inesdgomes If required I could change the spacing to be the exact same way which is 26px. I changed it to 24px so that we are sticking with multiples of 4.

**Comment by justintemps** [comment]
@Shashika6 We tested on the website and this looks fine as is. Thanks!

**Pull request merged**
