### PR TITLE
Add dark overlay when search bar is open

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes https://github.com/international-labour-organization/designsystem/issues/783

### Notes

* Add dark overlay when search is open

### Screenshot

Screenshot 2024-09-09 at 10 38 57

### CODE REVIEW

**Comment by Shashika6** [comment]
@justintemps what do you think about this implementation :)

**Comment by Shashika6** [comment]
Looks like theres an issue with the build in twig @GGKapanadze said he will have a look at it.

**Comment by GGKapanadze** [comment]
The styling issue is resolved right now we have to check why the search isn't propagating the correct js inside the base theme. \cc @Shashika6

**Comment by Shashika6** [comment]
Thanks @GGKapanadze will have a look a this one.

**Comment by Shashika6** [comment]
@justintemps this seems to be okay now will do a bit more testing on this and this should be ready :)

**Comment by Shashika6** [comment]
This is ready for review :)

**Comment by justintemps** [comment]
Hey @Shashika6 I think this needs a closer look. The transitions look really janky to me. 

1. Why is the search menu sliding out from the top blue part of the nav?
2. The search icon blinks weirdly when you click on it

It's not a very smooth user experience.

https://github.com/user-attachments/assets/7243405c-ce9e-4b64-914d-be8fffcf18b9

**Comment by Shashika6** [comment]
Sure @justintemps, Will fix the UX issues.

**Comment by Shashika6** [comment]
Hey @justintemps I fixed the transition issues you mentioned can you have a look now :)

**Pull request closed without merging**
