### PR TITLE
fix(style) : Spacing issues in cards

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes https://github.com/international-labour-organization/designsystem/issues/469

### Notes :- 

Verified all of the cards

- [x] **Multilink card**: revise all spacings in the multilink card, including top, left, right and bottom padding; before/after heading; before/after image; before/after description text

- [x] **Stats card**: revise space between last card and CTA on desktop and mobile

- [x] **Profiles**: align 'Learn more' button to name and title

- [x] **Card with short description**: fix space between eyebrow, title and description; fix space between image and grey line.

### CODE REVIEW

**Comment by Shashika6** [comment]
Screenshot 2023-10-03 at 14 56 11

**Comment by justintemps** [comment]
hey @Shashika6 correct me if I'm wrong, but here it looks like we're just updating the same spacing values using the new `spacing` mixin, right?

**Comment by Shashika6** [comment]
Yes @justintemps for now its like that waiting on the comment above to proceed with it

**Comment by Shashika6** [comment]
@justintemps I think we can merge this, verified that the spacing is in sync with the design as well. The changes are using the new spacing function.

**Comment by justintemps** [comment]
@Shashika6 just to confirm, the only thing this does is uses the new spacing mixin, it doesn't actually change any of the spacing right?

**Comment by Shashika6** [comment]
Yes @justintemps thats correct

**Comment by justintemps** [comment]
Ok @Shashika6 then I think we should change the changeset message, because it doesn't actually fix any spacing issues, it just uses a mixin to apply the same sizes that were there before.

**Comment by Shashika6** [comment]
Updated the changeset message @justintemps

**Pull request merged**
