### PR TITLE
fix(react/twig) - Tab navigation improvements in navigation 

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes https://github.com/international-labour-organization/designsystem/issues/863

### Notes :- 

* Currently the tab navigation is not working as intended. 

### Issues fixed :- 

- [x] Language selector is selected first instead of the logo.
- [x] Can't tab through the options in the language selector.
- [x] When you get to the Search tab. If you continue tabbing, instead of restarting the tab navigation it opens the search window.

### Demo :- 

https://github.com/international-labour-organization/designsystem/assets/32934169/50379699-fbb7-4b8a-ae9f-3ea3fcbfd2ed

### Solution :- 

* Refactor CSS to use display instead of visibility

### CODE REVIEW

**Comment by justintemps** [comment]
Hey @Shashika6 this works as expected on Chrome, but not on Firefox. Can you check?

**Comment by Shashika6** [comment]
Will test it out in firefox with your settings as well. @justintemps

**Comment by Shashika6** [comment]
Hey @justintemps had a look into this and finally figured out the issue on why this is happening. 

* I tested the preview in **windows with firefox** and everything is working as expected. 

* This is a known issue in **mac os with firefox**.

**Cause :** 

* By default the keyboard navigation is toggled off in mac os. 
* For the tab navigation to work in mac os with firefox we have to enable this toggle first from system settings. 
* After enabling the toggle the tab navigation should work as expected. 

How to enable keyboard navigation. 

System settings -> Keyboard -> Keyboard Navigation

**Comment by justintemps** [comment]
Hey @Shashika6 you're right about tab navigation on Firefox, thanks for the tip!

As for this solution, you're right that it solves the problem, but in doing so it breaks the animations when the search windows and submenu scroll out from the bottom. We should be able to have both nice transitions as well as an accessible menu. 

Using `display: none` might well be part of the solution here, but I think you're going to have use some JavaScript to time it so that it's not added until after the menu transitions are finished.

**Comment by justintemps** [comment]
@Shashika6 on closer inspection actually, I don't think we need `display: none` at all here, we can just dynamically set the tab index on the sub menu. I'm going to do this now.

**Comment by justintemps** [comment]
@Shashika6 on closer inspection, setting tab index won't work because it's not an inherited property. So I went back to the first idea of dynamically adding `display: none` after the close transition was run and then removing it before the open transition. This was a bit of a hack, but I checked in Chrome, Safari and Firefox and it seems to work everywhere.

**Comment by Shashika6** [comment]
Damn, this was a very tricky one good one @justintemps 🎉

**Comment by justintemps** [comment]
Hey @Shashika6, this should be ready to check now, could you have a look? make sure to test in mobile as well please. I'll try to test this with bb8 after lunch.

**Comment by Shashika6** [comment]
Works well in both firefox and chrome @justintemps should test this in mobile.

**Comment by justintemps** [comment]
> Works well in both firefox and chrome @justintemps should test this in mobile.

Yea would you mind doing that?

**Comment by Shashika6** [comment]
Navigation works as expected in mobile as well @justintemps

**Pull request merged**
