### PR TITLE
fix(docs): design bugs on welcome page

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes https://github.com/international-labour-organization/designsystem/issues/1188

### Notes

* Fix triangle going above text on welcome screen
* Fix get started link not showing 
* Sync styles with react and twig.

Screenshot 2024-09-05 at 12 27 21

### CODE REVIEW

**Comment by Shashika6** [comment]
@justintemps there was also an issue where the get started link was not showing. I fixed it up on this one as well let me know what you think :)

**Comment by justintemps** [comment]
Hey @Shashika6, I like the Get Started link, but let's make it a button and move it lower down, no?

**Comment by Shashika6** [comment]
Hey @justintemps, I converted the link to a button can you have a look :)

**Comment by justintemps** [comment]
@Shashika6 Perfect!

**Comment by justintemps** [comment]
Hey @Shashika6 I just merged this but it seems like the button doesn't work, could you check?

**Pull request merged**
