### PR TITLE
feat(twig): add aria-label attribute to modal

### PR DESCRIPTION
**Pull request by Shashika6**
Fixes https://github.com/international-labour-organization/designsystem/issues/765

### Notes :- 

* Added aria label attribute to modal in twig.
* **Added modalLabel as an optional param as it would break the existing implementation**

### CODE REVIEW

**Comment by justintemps** [comment]
Hey @Shashika6 really sorry! I looked into this and the error is a little misleading, evidently what's actually needed here is an `aria-label` attribute. So may be the argument should be `modalLabel` or something? 

See more info here: https://dequeuniversity.com/rules/axe/4.7/aria-dialog-name

**Comment by Shashika6** [comment]
Will do @justintemps I'll update the changes and add a comment

**Comment by justintemps** [comment]
Thanks @Shashika6 could we be just a little more descriptive in Storybook about what the argument is for? It should be clear that's it's for accessibility.

**Comment by Shashika6** [comment]
Updated the description @justintemps

**Pull request merged**
