### PR TITLE
fix(style) - increase underline offset

### PR DESCRIPTION
**Pull request by Shashika6**
This is a draft PR to test the underline offset

### CODE REVIEW

**Comment by justintemps** [comment]
Hey @Shashika6 this still doesn't work predictably, see below

https://github.com/international-labour-organization/designsystem/assets/12401179/6a798f90-6abf-4df6-afb6-6b82f72e3ee5

**Comment by Shashika6** [comment]
Can you check this now @justintemps

**Comment by justintemps** [comment]
Still no good @Shashika6, the background color applied on background is cover up the underline

image

**Comment by Shashika6** [comment]
Hey @justintemps I checked out with multiple values but there is no option that satisfies both the  offset issue and characters like g breaking the underline. 

A possible solution would be to increase the line-height what do you think ?

**Comment by justintemps** [comment]
hey @Shashika6, I think the problem is the background color added to the link. What happens if we remove that in the RichText?

**Comment by Shashika6** [comment]
Tried removing the background color in richtext @justintemps It doesn't seem to have any effect.

**Comment by justintemps** [comment]
@Shashika6 this is all you had to do: https://github.com/international-labour-organization/designsystem/pull/1048/files

**Pull request closed without merging**
