### PR TITLE
build(react) - Upgrade storybook to 7.6.6

### PR DESCRIPTION
**Pull request by Shashika6**
## Notes

*  Upgraded react story book to **v7.6.6**

## Steps followed

* Ran npx @storybook/upgrade@7.6.6
* Verify dependencies that were changed
* Cleaned and re-installed packages and rebuild repos. 
* Tested storybook in react
* Tested storybook in twig

Screenshot 2023-12-26 at 23 26 42

### CODE REVIEW

**Comment by justintemps** [comment]
Hey @Shashika6 remember that we only ever have changesets for changes to library code, changes to documentation (Storybook) code should not affection versioning.

**Comment by Shashika6** [comment]
> Hey @Shashika6 remember that we only ever have changesets for changes to library code, changes to documentation (Storybook) code should not affection versioning.

Gotcha @justintemps :)

**Comment by justintemps** [comment]
Also, @Shashika6 it looks like you have a conflict in the pnpm-lock.yaml. I think you'll need to merge `develop` into this branch, run `pnpm install` again and then check in the `pnpm-lock.yaml`

**Comment by Shashika6** [comment]
Fixed the merge conflicts @justintemps :)

**Pull request merged**
