### PR TITLE
Style(react): Hero card date position

### PR DESCRIPTION
**Pull request by Shashika6**
Change : - 

* Change the position of the date to be below the description as required in the design

Issue link :- https://github.com/international-labour-organization/designsystem/issues/568

### CODE REVIEW

**Comment by justintemps** [comment]
Thanks for this @Shashika6! A few things:

1. Let's also make the same change in the Twig package
2. This PR will eventually need a changeset. More info about that here: https://github.com/international-labour-organization/designsystem/blob/develop/contributing.md#versioning

**Comment by bashlk** [comment]
@Shashika6 The changeset is missing.

**Comment by Shashika6** [comment]
Sorry about that @bashlk @justintemps Added the changeset as well :)

**Review by justintemps — APPROVED** [review]
This looks good, thanks!

**Review by bashlk — APPROVED** [review]

**Comment by Shashika6** [comment]
@justintemps Will you be able to merge this one :)

**Pull request merged**
