### PR TITLE
ci(github): added twig cypress tests to test workflow

### LINKED ISSUE #947: Implement test setup for twig components
Setup the npm scripts and GitHub workflow to run cypress locally and on GitHub Actions.

### PR DESCRIPTION
**Pull request by bashlk**
Fixed #947

This PR makes the cypress tests for twig run within the test workflow. To do this, it spins up a docker container using the ilo base theme image and overwrites the build artifacts inside the image with the artifacts generated in the workflow.  It then runs the cypress tests against this container.

I also updated the version of all the actions that are being used in the workflow and fixed the caching of pnpm dependencies. It drops the matrix runner since Mac OS runners don't support running docker.

### CODE REVIEW

**Comment by justintemps** [comment]
Hey @bashlk is this ready to merge now?

**Comment by bashlk** [comment]
Hi @justintemps, no it isn't - I intended to create this as a draft PR but accidentally created it as a normal PR. I needed to create it because Github often does not trigger GitHub Actions for branches that don't have a PR. I will edit this PR and let you know once it is ready to merge.

**Comment by bashlk** [comment]
For some reason, the GitHub Action keeps getting cancelled - have we hit some kind of quota limit?

**Comment by justintemps** [comment]
Not that I'm aware of...

**Comment by bashlk** [comment]
@justintemps This is now ready to merge.

**Comment by justintemps** [comment]
Hey @bashlk weren't we going to remove the macos actions?

**Pull request merged**
